from typing import Any

def sniper_edit(
    filepath: str,
    start: int,
    end: int,
    content: str,
    auto_indent: bool | None = None,
    force_indent: bool | None = None,
    context_hash: str | None = None,
    dry_run: bool | None = None,
) -> dict[str, Any]: ...
def sniper_delete(filepath: str, start: int, end: int) -> dict[str, Any]: ...
def sniper_manifest(
    filepath: str,
    operations_json: str,
    auto_indent: bool | None = None,
    force_indent: bool | None = None,
    context_hash: str | None = None,
    dry_run: bool | None = None,
) -> dict[str, Any]: ...
def sniper_undo(filepath: str) -> str: ...
def sniper_encode(text: str) -> str: ...
def sniper_decode(hex_str: str) -> str: ...
def sniper_read_file(filepath: str) -> str: ...
def sniper_config() -> dict[str, Any]: ...
def validate_indentation_py(
    filepath: str, start: int, end: int, content: str
) -> dict[str, Any]: ...
def auto_indent_content_py(filepath: str, start: int, end: int, content: str) -> str: ...
def needs_indent_fix_py(filepath: str, start: int, end: int, content: str) -> bool: ...
def verify_context_py(
    filepath: str, start: int, end: int, expected_hash: str
) -> dict[str, Any]: ...
def recommend_from_risk_py() -> str: ...
def write_atomic_with_dal_py(filepath: str, content: str, dal_level: str) -> dict[str, Any]: ...
def check_file_size_py(filepath: str, max_size: int) -> bool: ...
def normalize_path_py(path: str) -> str: ...
def create_backup_py(filepath: str) -> str: ...
def find_latest_backup_py(filepath: str) -> str | None: ...
def count_recent_backups_py(filepath: str, window_secs: int) -> int: ...
def purge_old_backups_py(filepath: str, retention_count: int, max_age_days: int) -> int: ...
def version_py() -> dict[str, Any]: ...
def generate_preview_py(
    filepath: str, start: int, end: int, replacement: str
) -> dict[str, Any]: ...
